"""Backward-ephemeris capture-node generation (escape.propagate_escape's
``ephemeris_time_direction`` knob).

A Mars CAPTURE is the time-reverse of an escape. A capture node is generated by
running the escape law with the sail state integrating forward as
usual but the Sun/Mars EPHEMERIS clocked BACKWARD (``ephemeris_time_direction
= -1``): the sail spirals out under a backward-walking Sun, and the far
Hill-sphere endpoint's time-reverse is a real, forward-Sun capture. These tests
pin:

1. the knob defaults to +1 and reproduces forward propagation exactly;
2. a control-law-independent round-trip closes (forward +1, then negate v and
   run -1 returns to the start) -- the integrator + epoch-direction threading
   reverse correctly. The opposite direction closes to ~15 km versus ~1e-7 km for
   the correct direction, so the 1e-3 km tolerance
   separates correct from incorrect by ~4 orders of magnitude;
3. a positive signal: the escape law under -1 still spirals out (a grows) and
   the -1 trajectory genuinely differs from the +1 trajectory (the Sun geometry
   is different) -- the knob changes the physics, it is not a no-op.
"""
from __future__ import annotations

import math

import numpy as np
import pytest

from reflectors.attitude_control import AttitudeLimits
from reflectors.dynamics import mars_gm_km3_per_s2
from reflectors.ephemeris import utc_to_et
from reflectors.escape import (
    initial_circular_state,
    propagate_escape,
    time_reversed_capture_initial_state,
)
from reflectors.escape_dedot import DEdotParams, dedot_steer
from reflectors.gauss import osculating_elements
from reflectors.mars_constants import MARS_HILL_RADIUS_KM
from reflectors.qlaw import QLawParams
from reflectors.sail_designs import make_canonical_sail
from reflectors.termination import AltitudeFloor

R_EQ = 3396.19
EPOCH = "2028-01-01T00:00:00"


def _setup(altitude_km=1500.0):
    epoch_et = utc_to_et(EPOCH)
    state0 = initial_circular_state(altitude_km, epoch_et)
    sail = make_canonical_sail(0.018)
    qlaw_shell = QLawParams(a_target_km=MARS_HILL_RADIUS_KM, rp_min_km=R_EQ + 300.0)
    limits = AttitudeLimits(
        alpha_max_rad_s2=math.radians(0.003), omega_max_rad_s=math.radians(0.3)
    )
    mu = mars_gm_km3_per_s2()
    period = 2.0 * math.pi * math.sqrt(np.linalg.norm(state0[:3]) ** 3 / mu)
    return epoch_et, state0, sail, qlaw_shell, limits, mu, period


# Reference resolution for capture/escape reversibility. A function rather than
# a module-level dictionary ensures that AltitudeFloor.at_km reads the Mars
# radius only after the session kernel fixture loads the pool.
def _res():
    return dict(
        gravity_degree=2, steps_per_orbit=200,
        max_step_true_anomaly_deg=0.25, max_step_s=20.0,
        altitude_floor=AltitudeFloor.at_km(300.0),
    )


def _naive_escape_steering(mu):
    params = DEdotParams(max_cone_rad=math.radians(80.0), rp_warn_km=None,
                         mu_km3_s2=mu)

    def steering(r, v, s_hat, p_eff, sail_, current_n_hat):
        return dedot_steer(r, v, s_hat, p_eff, sail_,
                           current_n_hat=current_n_hat, params=params).n_star_j2000

    return steering


# ---------------------------------------------------------------------------
# 1. Default +1 is byte-identical (behaviour-preserving knob)
# ---------------------------------------------------------------------------


def test_ephemeris_time_direction_default_is_forward_byte_identical():
    epoch_et, state0, sail, qlaw_shell, limits, mu, period = _setup()
    span = 2.0 * period
    steering = _naive_escape_steering(mu)
    default = propagate_escape(
        state0, epoch_et, sail, qlaw_shell, limits, (0.0, span),
        steering_fn=steering, **_res(),
    )
    explicit_fwd = propagate_escape(
        state0, epoch_et, sail, qlaw_shell, limits, (0.0, span),
        steering_fn=steering, ephemeris_time_direction=+1, **_res(),
    )
    assert np.array_equal(default.t_s, explicit_fwd.t_s)
    assert np.array_equal(
        default.orbit_state_km_kmps, explicit_fwd.orbit_state_km_kmps
    )
    assert np.array_equal(default.attitude_state, explicit_fwd.attitude_state)
    assert default.metadata["ephemeris_time_direction"] == +1


def test_ephemeris_time_direction_rejects_invalid():
    epoch_et, state0, sail, qlaw_shell, limits, mu, period = _setup()
    with pytest.raises(ValueError, match="ephemeris_time_direction"):
        propagate_escape(
            state0, epoch_et, sail, qlaw_shell, limits, (0.0, period),
            ephemeris_time_direction=0, **_res(),
        )


# ---------------------------------------------------------------------------
# 2. Round-trip reversibility (control-law-independent)
# ---------------------------------------------------------------------------


def test_backward_ephemeris_round_trip_returns_to_start():
    """Forward (+1) a few purely-gravitational orbits from X0 -> X1; then from
    X1 with velocity NEGATED, backward (-1) for the same duration -> X0'. A
    correct integrator + epoch-direction threading returns to (r0, -v0). Uses
    force_coast + kinematic_attitude so SRP is exactly zero (no control-law
    asymmetry); the only epoch-dependent force is the Sun third body, so the
    closure directly exercises the backward-ephemeris threading."""
    epoch_et, state0, sail, qlaw_shell, limits, mu, period = _setup()
    span = 2.0 * period
    fwd = propagate_escape(
        state0, epoch_et, sail, qlaw_shell, limits, (0.0, span),
        force_coast=True, kinematic_attitude=True,
        ephemeris_time_direction=+1, **_res(),
    )
    x1 = fwd.orbit_state_km_kmps[-1].copy()
    t_end = float(fwd.t_s[-1])
    x1_vneg = x1.copy()
    x1_vneg[3:6] = -x1_vneg[3:6]
    back = propagate_escape(
        x1_vneg, epoch_et + t_end, sail, qlaw_shell, limits, (0.0, t_end),
        force_coast=True, kinematic_attitude=True,
        ephemeris_time_direction=-1, **_res(),
    )
    x0p = back.orbit_state_km_kmps[-1]
    dr = float(np.linalg.norm(x0p[:3] - state0[:3]))
    dv = float(np.linalg.norm(x0p[3:6] - (-state0[3:6])))
    assert dr < 1.0e-3, f"position closure {dr:.3e} km too large"
    assert dv < 1.0e-6, f"velocity closure {dv:.3e} km/s too large"


# ---------------------------------------------------------------------------
# 3. Positive signal: escape law + backward ephemeris spirals out
# ---------------------------------------------------------------------------


def test_backward_ephemeris_escape_law_spirals_out_and_differs_from_forward():
    epoch_et, state0, sail, qlaw_shell, limits, mu, period = _setup()
    span = 6.0 * period
    steering = _naive_escape_steering(mu)

    back = propagate_escape(
        state0, epoch_et, sail, qlaw_shell, limits, (0.0, span),
        steering_fn=steering, ephemeris_time_direction=-1, **_res(),
    )
    fwd = propagate_escape(
        state0, epoch_et, sail, qlaw_shell, limits, (0.0, span),
        steering_fn=steering, ephemeris_time_direction=+1, **_res(),
    )

    a0 = osculating_elements(state0[:3], state0[3:6], mu).a_km
    a_back = osculating_elements(
        back.orbit_state_km_kmps[-1][:3], back.orbit_state_km_kmps[-1][3:6], mu
    ).a_km
    # Positive signal: the escape law still adds energy under the reversed clock.
    assert a_back > a0 + 1.0
    assert back.metadata["ephemeris_time_direction"] == -1

    # Backward versus forward Sun geometry produces a different trajectory.
    sep = float(np.linalg.norm(
        back.orbit_state_km_kmps[-1][:3] - fwd.orbit_state_km_kmps[-1][:3]
    ))
    assert sep > 1.0, f"backward and forward trajectories barely differ ({sep:.3e} km)"


# ---------------------------------------------------------------------------
# 4. Capture-init velocity negation: the flown
#    forward capture is the time-reverse of the backward (spiral-out) run and so
#    ARRIVES with -v. To land in the DESIRED orbit the backward run must START at
#    (r, -v); without this the capture delivered the time-reversed SUPPLEMENT
#    orbit (retrograde sun-sync i -> prograde 180-i, which is not sun-sync).
# ---------------------------------------------------------------------------


def test_capture_init_negates_velocity_and_reverses_circulation():
    """``time_reversed_capture_initial_state`` keeps position and negates
    velocity, so the angular momentum (hence circulation / inclination sense)
    flips: ``h -> -h``, ``i -> 180 - i``."""
    desired = np.array([3904.0, 120.0, -45.0, 0.21, 1.02, -3.16])
    cap_init = time_reversed_capture_initial_state(desired)
    np.testing.assert_allclose(cap_init[:3], desired[:3])
    np.testing.assert_allclose(cap_init[3:], -desired[3:])
    h_des = np.cross(desired[:3], desired[3:])
    h_cap = np.cross(cap_init[:3], cap_init[3:])
    np.testing.assert_allclose(h_cap, -h_des, rtol=0, atol=1e-12)


def test_forward_capture_arrives_in_desired_orbit_not_supplement():
    """The flown forward capture is the time-reverse
    of the backward run (it negates velocity again), so starting the backward run
    at ``time_reversed_capture_initial_state(desired)`` makes the forward capture
    arrive in ``desired`` with the same circulation (``h`` matches), not its
    supplement. Omitting the negation would produce ``-h``."""
    desired = np.array([3904.0, 120.0, -45.0, 0.21, 1.02, -3.16])
    cap_init = time_reversed_capture_initial_state(desired)
    # the flown forward capture = time-reverse of the backward run = negate v again
    forward_arrival = np.concatenate([cap_init[:3], -cap_init[3:]])
    np.testing.assert_allclose(forward_arrival, desired, rtol=0, atol=1e-12)
    np.testing.assert_allclose(
        np.cross(forward_arrival[:3], forward_arrival[3:]),
        np.cross(desired[:3], desired[3:]), rtol=0, atol=1e-12,
    )


def test_capture_init_rejects_non_6_vector():
    with pytest.raises(ValueError):
        time_reversed_capture_initial_state(np.zeros(5))
